#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
BASE_DIR="$(basename $DIR)"

# Setup logging fifos.
[ ! -e /run/log/${BASE_DIR} ] && mkfifo /run/log/${BASE_DIR}

export RETHINKDB_ENV_AUTHKEY="$(cat ${X_STF_DATA_DIR}/rethinkdb.password)"
export STF_APP_SECRET="$(cat ${X_STF_DATA_DIR}/web_secret.password)"

exec stf app \
    --port ${X_STF_APP_PORT} \
    --auth-url https://${X_STF_PUBLIC_ADDR}/auth/mock/ \
    --websocket-url wss://${X_STF_PUBLIC_ADDR} \
    > /run/log/${BASE_DIR} 2>&1

