#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
BASE_DIR="$(basename $DIR)"

# Setup logging fifos.
[ ! -e /run/log/${BASE_DIR} ] && mkfifo /run/log/${BASE_DIR}

export RETHINKDB_ENV_AUTHKEY="$(cat ${X_STF_DATA_DIR}/rethinkdb.password)"
export STF_API_SECRET="$(cat ${X_STF_DATA_DIR}/web_secret.password)"

exec stf api \
    --port ${X_STF_API_PORT} \
    --connect-sub tcp://${X_STF_APPSIDE_ADDR}:7150 \
    --connect-push tcp://${X_STF_APPSIDE_ADDR}:7170 \
    --connect-sub-dev tcp://${X_STF_DEVSIDE_ADDR}:7250 \
    --connect-push-dev tcp://${X_STF_DEVSIDE_ADDR}:7270 \
    > /run/log/${BASE_DIR} 2>&1
