#!/bin/bash
SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done
DIR="$( cd -P "$( dirname "$SOURCE" )" >/dev/null 2>&1 && pwd )"
BASE_DIR="$(basename $DIR)"

# Setup logging fifos.
[ ! -e /run/log/${BASE_DIR} ] && mkfifo /run/log/${BASE_DIR}

export RETHINKDB_ENV_AUTHKEY="$(cat ${X_STF_DATA_DIR}/rethinkdb.password)"

exec stf triproxy dev \
    --bind-pub "tcp://${X_STF_DEVSIDE_ADDR}:7250" \
    --bind-dealer "tcp://${X_STF_DEVSIDE_ADDR}:7260" \
    --bind-pull "tcp://${X_STF_DEVSIDE_ADDR}:7270" \
    > /run/log/${BASE_DIR} 2>&1

